- id: standard-readme
  name: Standard Readme
  description: Check README compliance with standard-readme spec
  entry: npx -p remark-cli remark -u ./lint-readme -f
  language: node
  files: '^README.md$'
